module.exports = {
	entry:'./build/App.js',
	//创建一个入口文件（这里指的是源代码文件位置，因为我们组建的名称都是大写字母开头，所以我们把文件的名称也大写字母开头）
	output:{//输出，指定输出的目录以及文件名称
		path:"./js",//输出目录
		filename:"bundle.js"//输出的文件名称
	},
	//模块的处理
	module:{
		loaders:[
		{
			test:/\.js$/,//通过入口文件匹配所有的js文件
			loader:"jsx-loader"//通过jsx-loader加载器进行解析处理
			//loader:"jshint-loader"//检查拼写
		}
		]
	}
}
/*
1.通过入口，寻找入口里面调用的组件文件，自动处理其相互之间的依赖关系
2.代码整合，实现将a.js调用b.js，将所有的组件文件整合到一个大文件中
*/